---
- name: Gather build logs
  hosts: vps_runner
  gather_facts: true
  vars_files:
    - ../vars/main.yml

  tasks:
    - name: Copy logs
      fetch:
        src: "/home/ansible/{{ item }}"
        dest: "../logs/{{ item }}"
      with_items:
        - 'install_verified_source.log'
        - 'build.log'
