---
- name: Create install_verified_source script
  template:
    src: ../templates/install_verified_source.sh
    dest: /home/ansible/install_verified_source.sh
    mode: 0744

- name: Run install_verified_source script
  shell: "/home/ansible/install_verified_source.sh {{ lookup('env', 'GITHUB_REF_NAME') }} {{ lookup('env', 'REPO_URL') }} >> /home/ansible/install_verified_source.log 2>&1"
